<!-- RSSAM project code.
     Copyright (c) 2026 Daniel Riggi (riggi89).
     Attribution for modified SAM sources: LICENSE.md and NOTICE.md. -->

<Project>
  <PropertyGroup>
    <Version>1.0.30</Version>
    <AssemblyVersion>1.0.30</AssemblyVersion>
    <FileVersion>1.0.30</FileVersion>
    <Platforms>x86;x64</Platforms>
    <RSSAMArchitecture Condition="'$(Platform)' == 'x86'">x86</RSSAMArchitecture>
    <RSSAMArchitecture Condition="'$(Platform)' == 'x64'">x64</RSSAMArchitecture>
    <RSSAMArchitecture Condition="'$(RSSAMArchitecture)' == '' And '$(RuntimeIdentifier)' == 'win-x86'">x86</RSSAMArchitecture>
    <RSSAMArchitecture Condition="'$(RSSAMArchitecture)' == '' And '$(RuntimeIdentifier)' == 'win-x64'">x64</RSSAMArchitecture>
    <RSSAMArchitecture Condition="'$(RSSAMArchitecture)' == ''">x64</RSSAMArchitecture>
    <PlatformTarget>$(RSSAMArchitecture)</PlatformTarget>
    <RuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' And '$(BuildingForUnitTests)' != 'true' And '$(MSBuildProjectName)' != 'RSSAM.UnitTests'">win-$(RSSAMArchitecture)</RuntimeIdentifier>
    <DefineConstants Condition="'$(RSSAMArchitecture)' == 'x64'">$(DefineConstants);RSSAM_X64</DefineConstants>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
