# RSSAM original build script.
# Copyright (c) 2026 Daniel Riggi (riggi89).
# Distributed under the project license; see LICENSE.md and NOTICE.md.

#requires -Version 5.1

param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',

    [ValidateSet('x86', 'x64', 'All')]
    [string]$Architecture = 'All',

    [switch]$SkipClean
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
$appProject = Join-Path $root 'src\RSSAM.App\RSSAM.App.csproj'
$targetArchitectures = if ($Architecture -eq 'All') {
    @('x86', 'x64')
}
else {
    @($Architecture)
}

function New-SafeTemporaryDirectory {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Name
    )

    $tempRoot = [System.IO.Path]::GetTempPath()

    if ($tempRoot.Contains("'")) {
        throw (
            "The temporary directory contains an apostrophe and cannot be used " +
            "as the safe RSSAM build path: $tempRoot"
        )
    }

    $directory = Join-Path `
        $tempRoot `
        ("RSSAM-$Name-" + [Guid]::NewGuid().ToString('N'))

    New-Item -ItemType Directory -Path $directory -Force | Out-Null
    return $directory
}

function Ensure-WinUiResourceIndex {
    param(
        [Parameter(Mandatory = $true)][string]$OutputDirectory,
        [Parameter(Mandatory = $true)][string]$BuildRoot,
        [Parameter(Mandatory = $true)][string]$RuntimeIdentifier
    )

    $publishedResourceIndex = Join-Path $OutputDirectory 'resources.pri'
    if (Test-Path -LiteralPath $publishedResourceIndex) {
        return
    }

    # The isolated build root contains all intermediate/output files created by
    # this publish run, including the PRI generated by the WinUI build targets.
    $resourceIndex = Get-ChildItem `
        -LiteralPath $BuildRoot `
        -Filter '*.pri' `
        -File `
        -Recurse `
        -ErrorAction SilentlyContinue |
    Where-Object {
        $_.Name -in @('resources.pri', 'RSSAM.pri')
    } |
    Sort-Object LastWriteTimeUtc -Descending |
    Select-Object -First 1

    if ($null -ne $resourceIndex) {
        Copy-Item `
            -LiteralPath $resourceIndex.FullName `
            -Destination $publishedResourceIndex `
            -Force

        Write-Host "Recovered resources.pri for $RuntimeIdentifier from $($resourceIndex.FullName)"
    }
}

function Assert-PublishPayload {
    param(
        [Parameter(Mandatory = $true)][string]$OutputDirectory,
        [Parameter(Mandatory = $true)][string]$RuntimeIdentifier
    )

    $requiredFiles = @(
        'RSSAM.exe',
        'RSSAM.dll',
        'RSSAM.Core.dll',
        'RSSAM.API.dll',
        'WinUI.TableView.dll',
        'Microsoft.UI.Xaml.dll',
        'Microsoft.WindowsAppRuntime.dll',
        'resources.pri',
        'coreclr.dll',
        'hostfxr.dll',
        'hostpolicy.dll'
    )

    $missingFiles = @(
        $requiredFiles |
        Where-Object {
            -not (Test-Path -LiteralPath (Join-Path $OutputDirectory $_))
        }
    )

    if ($missingFiles.Count -gt 0) {
        throw (
            "Incomplete $RuntimeIdentifier publish output. Missing required files: " +
            ($missingFiles -join ', ')
        )
    }
}

function Copy-PublishPayload {
    param(
        [Parameter(Mandatory = $true)][string]$SourceDirectory,
        [Parameter(Mandatory = $true)][string]$DestinationDirectory
    )

    if (Test-Path -LiteralPath $DestinationDirectory) {
        Remove-Item -LiteralPath $DestinationDirectory -Recurse -Force
    }

    New-Item -ItemType Directory -Path $DestinationDirectory -Force | Out-Null

    Copy-Item `
        -Path (Join-Path $SourceDirectory '*') `
        -Destination $DestinationDirectory `
        -Recurse `
        -Force
}

function Invoke-IsolatedPublish {
    param(
        [Parameter(Mandatory = $true)][string]$TargetArchitecture,
        [Parameter(Mandatory = $true)][string]$RuntimeIdentifier,
        [Parameter(Mandatory = $true)][string]$DestinationDirectory
    )

    # A fresh root is used for every attempt. BaseIntermediateOutputPath and
    # BaseOutputPath are redirected by Directory.Build.props via RSSAMBuildRoot.
    # The normal src\*\bin and src\*\obj folders are never touched by publish.
    $attemptCount = 2

    for ($attempt = 1; $attempt -le $attemptCount; $attempt++) {
        $temporaryRoot = New-SafeTemporaryDirectory -Name "publish-$RuntimeIdentifier"
        $buildRoot = Join-Path $temporaryRoot 'build'
        $stagingDirectory = Join-Path $temporaryRoot 'publish'

        New-Item -ItemType Directory -Path $buildRoot -Force | Out-Null
        New-Item -ItemType Directory -Path $stagingDirectory -Force | Out-Null

        try {
            Write-Host ''
            Write-Host "Publishing RSSAM $RuntimeIdentifier (attempt $attempt/$attemptCount)..."
            Write-Host "Build    : $buildRoot"
            Write-Host "Staging  : $stagingDirectory"
            Write-Host "Output   : $DestinationDirectory"
            Write-Host ''

            # UseSharedCompilation=false keeps Roslyn from using the shared
            # compiler server for this publish. -m:1 prevents project build work
            # from running concurrently, which also avoids generated-file locks.
            & dotnet publish `
                $appProject `
                -c $Configuration `
                -p:Platform=$TargetArchitecture `
                -r $RuntimeIdentifier `
                --self-contained true `
                -p:SelfContained=true `
                -p:WindowsPackageType=None `
                -p:WindowsAppSDKSelfContained=true `
                -p:AppxGeneratePriEnabled=true `
                -p:ProjectPriFileName=resources.pri `
                -p:PublishSingleFile=false `
                -p:PublishTrimmed=false `
                -p:RSSAMBuildRoot=$buildRoot `
                -p:UseSharedCompilation=false `
                -m:1 `
                -nr:false `
                -o $stagingDirectory

            $publishExitCode = $LASTEXITCODE

            if ($publishExitCode -ne 0) {
                if ($attempt -lt $attemptCount) {
                    Write-Warning (
                        "dotnet publish failed for $RuntimeIdentifier with exit code " +
                        "$publishExitCode. Retrying once with a fresh isolated build root."
                    )
                    continue
                }

                throw "dotnet publish failed for $RuntimeIdentifier with exit code $publishExitCode."
            }

            Ensure-WinUiResourceIndex `
                -OutputDirectory $stagingDirectory `
                -BuildRoot $buildRoot `
                -RuntimeIdentifier $RuntimeIdentifier

            Assert-PublishPayload `
                -OutputDirectory $stagingDirectory `
                -RuntimeIdentifier $RuntimeIdentifier

            Copy-PublishPayload `
                -SourceDirectory $stagingDirectory `
                -DestinationDirectory $DestinationDirectory

            Assert-PublishPayload `
                -OutputDirectory $DestinationDirectory `
                -RuntimeIdentifier $RuntimeIdentifier

            Write-Host "Published and validated $RuntimeIdentifier to $DestinationDirectory"
            return
        }
        finally {
            if (Test-Path -LiteralPath $temporaryRoot) {
                Remove-Item `
                    -LiteralPath $temporaryRoot `
                    -Recurse `
                    -Force `
                    -ErrorAction SilentlyContinue
            }
        }
    }
}

# Older versions of this script deleted src\*\bin and src\*\obj before every
# publish. That can itself fail when Visual Studio has a generated file open.
# Isolated publish roots make repository cleanup unnecessary. -SkipClean is kept
# for command-line compatibility with existing scripts/workflows.
if (-not $SkipClean) {
    Write-Host 'Using isolated publish state; repository bin/obj cleanup is not required.'
}

foreach ($targetArchitecture in $targetArchitectures) {
    $runtimeIdentifier = "win-$targetArchitecture"
    $outputDirectory = Join-Path $root "artifacts\publish\$runtimeIdentifier"

    Invoke-IsolatedPublish `
        -TargetArchitecture $targetArchitecture `
        -RuntimeIdentifier $runtimeIdentifier `
        -DestinationDirectory $outputDirectory
}
